"""cleaning

Revision ID: 31b0e7d51d0e
Revises: 
Create Date: 2020-11-13 11:41:34.473299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b0e7d51d0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('msg_num', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msg_msg_num'), 'msg', ['msg_num'], unique=False)
    op.create_index(op.f('ix_msg_time'), 'msg', ['time'], unique=False)
    op.create_index(op.f('ix_msg_timestamp'), 'msg', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msg_timestamp'), table_name='msg')
    op.drop_index(op.f('ix_msg_time'), table_name='msg')
    op.drop_index(op.f('ix_msg_msg_num'), table_name='msg')
    op.drop_table('msg')
    # ### end Alembic commands ###
