"""allow sames msg numbers

Revision ID: 20ebb8663ae9
Revises: 3d6ad06543eb
Create Date: 2020-11-11 19:33:03.689004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ebb8663ae9'
down_revision = '3d6ad06543eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_msg_msg_num', table_name='msg')
    op.create_index(op.f('ix_msg_msg_num'), 'msg', ['msg_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msg_msg_num'), table_name='msg')
    op.create_index('ix_msg_msg_num', 'msg', ['msg_num'], unique=1)
    # ### end Alembic commands ###
