"""empty message

Revision ID: 3d6ad06543eb
Revises: 45295f128aa6
Create Date: 2020-11-11 19:28:56.287680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6ad06543eb'
down_revision = '45295f128aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msg', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_msg_timestamp'), 'msg', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msg_timestamp'), table_name='msg')
    op.drop_column('msg', 'timestamp')
    # ### end Alembic commands ###
