"""msg table

Revision ID: 45295f128aa6
Revises: 
Create Date: 2020-11-11 14:10:34.341780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45295f128aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_num', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msg_msg_num'), 'msg', ['msg_num'], unique=True)
    op.create_index(op.f('ix_msg_time'), 'msg', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msg_time'), table_name='msg')
    op.drop_index(op.f('ix_msg_msg_num'), table_name='msg')
    op.drop_table('msg')
    # ### end Alembic commands ###
