"""erasing data

Revision ID: 86265c7b61e3
Revises: 20ebb8663ae9
Create Date: 2020-11-11 19:55:52.364213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86265c7b61e3'
down_revision = '20ebb8663ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_msg_timestamp'), 'msg', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msg_timestamp'), table_name='msg')
    # ### end Alembic commands ###
