version: "3"
services: 
  ml-app:
    build: .
    ports: 
      - "5000"
    volumes:
      - ./:/pythonapp
  nginx:
    image: nginx:latest
    
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ml-app
    ports:
      - "5000:80"

