version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server

  worker6:
    image: master-image
    depends_on:
      - redis
    entrypoint: venv/bin/rq worker msg_tasks --url redis://redis:6379/0

  model423:
    build: .
    image: master-image
    ports:
     - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    entrypoint: ["./boot.sh"]





