version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server

  # worker:
  #   image: jaredv/rq-docker:0.0.2 
  #   depends_on:
  #     - redis
  #   command: rqworker --name msg_tasks --url redis://redis:6379/0

  worker:
    depends_on:
      - redis
      - model404
    command: rq worker msg_tasks --url redis://redis:6379/0


  model405:
    build: .
    ports:
     - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

