version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server

  consumer405:
    build: .
    image: main
    ports:
     - "5000:5000"
    links:
       - "mysql:mysql"
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: mysql
      DB_NAME: model
      DB_USER: model
      DB_PASSWORD: slimdingo85
    depends_on:
      - redis
      - mysql
    entrypoint: ["./boot.sh"]

  rq_worker400:
    image: main:latest
    depends_on:
      - redis
    entrypoint: venv/bin/rq worker msg_tasks --url redis://redis:6379/0

  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: slimdingo85
      MYSQL_DATABASE: model
      MYSQL_USER: model
      MYSQL_PASSWORD: slimdingo85

volumes:
    mysql-data:







